name: Test Plugin

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch: 

jobs:
  test:
    strategy:
      matrix:
        runtime: ['paper', 'spigot', 'purpur']
        version: ['1.21.11', '1.20.6', '1.19.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - uses: SpraxDev/Action-SpigotMC@v5
        with:
          versions: 1.19.4, 1.19.3, 1.19.2
          remapped: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - uses: SpraxDev/Action-SpigotMC@v5
        with:
          versions: 1.21.11, 1.21.10, 1.21.8, 1.21.5, 1.21.4, 1.21.3, 1.21.2, 1.20.6, 1.20.4, 1.20.2, 1.20.1
          remapped: true
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-java-app-package
          path: target/Alkatraz.jar
      - uses: NagasonicDev/TestMC@v1.0.0
        with:
          path: 'target/Alkatraz.jar'
          runtime: ${{ matrix.runtime }}
          version: ${{ matrix.version }}
          time: 120
          commands: |
            version
